<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-05-25T15:09:09</date>
  <millis>1527271749826</millis>
  <sequence>0</sequence>
  <logger>java.util.logging.Logger</logger>
  <level>SEVERE</level>
  <class>utilidades.Log</class>
  <method>gravaLog</method>
  <thread>1</thread>
  <message>com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'</message>
  <exception>
    <message>com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'</message>
    <frame>
      <class>sun.reflect.NativeConstructorAccessorImpl</class>
      <method>newInstance0</method>
    </frame>
    <frame>
      <class>sun.reflect.NativeConstructorAccessorImpl</class>
      <method>newInstance</method>
    </frame>
    <frame>
      <class>sun.reflect.DelegatingConstructorAccessorImpl</class>
      <method>newInstance</method>
    </frame>
    <frame>
      <class>java.lang.reflect.Constructor</class>
      <method>newInstance</method>
    </frame>
    <frame>
      <class>com.mysql.jdbc.Util</class>
      <method>handleNewInstance</method>
      <line>425</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.Util</class>
      <method>getInstance</method>
      <line>408</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.SQLError</class>
      <method>createSQLException</method>
      <line>936</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.MysqlIO</class>
      <method>checkErrorPacket</method>
      <line>3976</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.MysqlIO</class>
      <method>checkErrorPacket</method>
      <line>3912</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.MysqlIO</class>
      <method>sendCommand</method>
      <line>2530</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.MysqlIO</class>
      <method>sqlQueryDirect</method>
      <line>2683</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.ConnectionImpl</class>
      <method>execSQL</method>
      <line>2486</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.PreparedStatement</class>
      <method>executeInternal</method>
      <line>1858</line>
    </frame>
    <frame>
      <class>com.mysql.jdbc.PreparedStatement</class>
      <method>execute</method>
      <line>1197</line>
    </frame>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>insereLivro</method>
      <line>101</line>
    </frame>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>populaTabelas</method>
      <line>544</line>
    </frame>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>&lt;init&gt;</method>
      <line>38</line>
    </frame>
    <frame>
      <class>main.Contexto</class>
      <method>&lt;init&gt;</method>
      <line>28</line>
    </frame>
    <frame>
      <class>main.Main</class>
      <method>main</method>
      <line>21</line>
    </frame>
  </exception>
</record>
<record>
  <date>2018-05-25T15:09:09</date>
  <millis>1527271749830</millis>
  <sequence>1</sequence>
  <logger>java.util.logging.Logger</logger>
  <level>SEVERE</level>
  <class>utilidades.Log</class>
  <method>gravaLog</method>
  <thread>1</thread>
  <message>basedados.BaseDadosException: Erro ao setar os parâmetros da consulta.</message>
  <exception>
    <message>basedados.BaseDadosException: Erro ao setar os parâmetros da consulta.</message>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>insereLivro</method>
      <line>104</line>
    </frame>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>populaTabelas</method>
      <line>544</line>
    </frame>
    <frame>
      <class>basedados.GerenciadorBaseDadosJDBC</class>
      <method>&lt;init&gt;</method>
      <line>38</line>
    </frame>
    <frame>
      <class>main.Contexto</class>
      <method>&lt;init&gt;</method>
      <line>28</line>
    </frame>
    <frame>
      <class>main.Main</class>
      <method>main</method>
      <line>21</line>
    </frame>
  </exception>
</record>
